[package]
name = "vss"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
glob = "0.3.3"
gray_matter = "0.2"
markdown = "1.0.0"
noargs = "0.4.1"
ramhorns = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
toml = "0.8"
