site_title = "Example Site"
site_description = "An example site built with vss"
base_url = "https://example.com"

[build]
ignore_files = ["README.md"]

[build.markdown]
# この設定を true にすることで Markdown 内に記載した HTML のコメントアウトが有効になります
# この設定が false だとコメントアウトは文字列として処理されてしまいます
allow_dangerous_html = false

